# Generated by Django 4.2.20 on 2025-03-15 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("portfolios", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="holding",
            name="portfolio",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="holdings",
                to="portfolios.portfolio",
            ),
        ),
        migrations.AddConstraint(
            model_name="holding",
            constraint=models.CheckConstraint(
                check=models.Q(("quantity__gt", 0)), name="positive_quantity"
            ),
        ),
    ]
