# Generated by Django 4.2.20 on 2025-03-15 14:53

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolios", "0002_alter_holding_portfolio_holding_positive_quantity"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="stockprice",
            name="non_negative_price",
        ),
        migrations.AddConstraint(
            model_name="stockprice",
            constraint=models.CheckConstraint(
                check=models.Q(("price__gt", Decimal("0"))), name="positive_price"
            ),
        ),
    ]
