services:
  portfolios-web:
    build:
      context: .
    command: ./runserver.sh
    ports:
      - 8000:8000
    environment:
      - DJANGO_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_EMAIL=admin@example.com
      - DJANGO_SUPERUSER_PASSWORD=hunter2
